name: Build and deploy to Kuroco front

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Generate project
        run: npm run generate

      - name: Validate kuroco_front.json exists and is valid JSON
        run: |
          if [ -f "./.output/public/kuroco_front.json" ]; then
            echo "kuroco_front.json found"
            if jq empty ./.output/public/kuroco_front.json; then
              echo "kuroco_front.json is valid JSON"
            else
              echo "Error: kuroco_front.json is not valid JSON"
              exit 1
            fi
          else
            echo "Error: kuroco_front.json not found in .output/public folder"
            exit 1
          fi

      - name: Zip artifact for upload
        run: cd ./.output/public && zip ../../dist.zip . -r

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact-${{ github.sha }}
          path: dist.zip
          retention-days: 7

      - name: Trigger webhook
        uses: diverta/workflow-webhook@v3
        with:
          webhook_url: "https://malias-2025-3-29.g.kuroco.app/direct/menu/github/"
          webhook_secret: "fa824a353087e6ee3578efdf3ba5bd33"
          data: '{"single_zip":"1","domain":"malias-2025-3-29.g.kuroco-front.app","repository":"${{ github.repository }}","run_id":"${{ github.run_id }}","hash":"${{ github.sha }}"}'
